# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recsys.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecsys.proto\x12\rrecsys_engine\",\n\x12\x43ommunitiesRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x03\x12\t\n\x01k\x18\x02 \x01(\x05\"(\n\tCommunity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"D\n\x13\x43ommunitiesResponse\x12-\n\x0b\x63ommunities\x18\x01 \x03(\x0b\x32\x18.recsys_engine.Community2d\n\x0cRecSysEngine\x12T\n\x0b\x43ommunities\x12!.recsys_engine.CommunitiesRequest\x1a\".recsys_engine.CommunitiesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recsys_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMUNITIESREQUEST']._serialized_start=31
  _globals['_COMMUNITIESREQUEST']._serialized_end=75
  _globals['_COMMUNITY']._serialized_start=77
  _globals['_COMMUNITY']._serialized_end=117
  _globals['_COMMUNITIESRESPONSE']._serialized_start=119
  _globals['_COMMUNITIESRESPONSE']._serialized_end=187
  _globals['_RECSYSENGINE']._serialized_start=189
  _globals['_RECSYSENGINE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
