# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recsys_pb2 as recsys__pb2


class RecSysEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Communities = channel.unary_unary(
                '/recsys_engine.RecSysEngine/Communities',
                request_serializer=recsys__pb2.CommunitiesRequest.SerializeToString,
                response_deserializer=recsys__pb2.CommunitiesResponse.FromString,
                )


class RecSysEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Communities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecSysEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Communities': grpc.unary_unary_rpc_method_handler(
                    servicer.Communities,
                    request_deserializer=recsys__pb2.CommunitiesRequest.FromString,
                    response_serializer=recsys__pb2.CommunitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recsys_engine.RecSysEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecSysEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Communities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recsys_engine.RecSysEngine/Communities',
            recsys__pb2.CommunitiesRequest.SerializeToString,
            recsys__pb2.CommunitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
